version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HUGGINGFACE_MODEL_ID=${HUGGINGFACE_MODEL_ID}
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: